<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
	'__library_version__' => 2,
	'class'               => array(
		'PHPUnit7Engine' => 'lib/PHPUnit7Engine.php',
		'PHPUnit7Parser' => 'lib/PHPUnit7Parser.php',
	),
	'function'            => [],
	'xmap'                => array(
		'PHPUnit7Engine' => 'ArcanistUnitTestEngine',
		'PHPUnit7Parser' => 'ArcanistTestResultParser',
	),
));
